# Generated by Django 4.2.2 on 2023-06-25 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('deleted_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('deleted_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishLists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.users')),
            ],
        ),
        migrations.CreateModel(
            name='WishListBooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('deleted_at', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.books')),
                ('wish_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.wishlists')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCarts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.users')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartBooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('deleted_at', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.books')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.shoppingcarts')),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('deleted_at', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.books')),
            ],
        ),
        migrations.CreateModel(
            name='BookComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.users')),
            ],
        ),
    ]
