# Generated by Django 4.2.2 on 2023-07-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
