# Generated by Django 4.2.2 on 2023-07-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0003_alter_wishlistbooks_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlists',
            name='wishlist_name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
