# Generated by Django 4.2.2 on 2023-07-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0008_alter_users_created_at_alter_users_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
    ]
