# Generated by Django 4.2.2 on 2023-07-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0010_remove_users_name_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
    ]
