# Generated by Django 4.2.2 on 2023-07-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0012_alter_users_name_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
