# Generated by Django 4.2.2 on 2023-07-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0015_users_last_login_alter_users_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
