# Generated by Django 3.2.12 on 2023-07-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0002_bookdetails_price'),
        ('djangoBookStoreApi', '0020_alter_users_username'),
    ]

    operations = [
    ]
