# Generated by Django 4.2.2 on 2023-07-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0022_bookcomments_created_at_bookcomments_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
