# Generated by Django 4.2.2 on 2023-07-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0023_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomments',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookcomments',
            name='deleted_at',
        ),
    ]
