# Generated by Django 4.2.2 on 2023-07-12 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0024_remove_bookcomments_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRatings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.SmallIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.users')),
            ],
        ),
    ]
